version: 2
mergeable:
  - when: pull_request
    name: 'Approval check'
    validate:
      - do: approvals
        min:
          count: 1
        limit:
          users: [ 'sofyak0zyreva', 'shvorobsofia' ]